# Generated by Django 5.2.6 on 2025-10-27 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Casa'), (2, 'Apartamento'), (3, 'Terreno'), (3, 'Comercial'), (4, 'Chácara'), (5, 'Prédio')])),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('quartos', models.IntegerField(blank=True, null=True)),
                ('banheiros', models.IntegerField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_publicacao', models.DateTimeField(default=datetime.datetime.now)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imoveis/')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
