# Generated by Django 5.2.6 on 2025-11-27 15:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[(1, 'Gerente'), (2, 'Corretor'), (3, 'Assistente Administrativo'), (4, 'Funcionária de Limpeza'), (5, 'Segurança'), (6, 'Estagiário'), (7, 'Outro'), (0, 'Não há funcionários')], max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_contratacao', models.DateField(default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='imoveis.imoveis')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
